### ISSUE TITLE
Option for `bw verify` to only show items that need fixing

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#127]

**Comment by vain** [comment]
I've implemented this on "verify-only-fixing".

However, I think it's better to make this the default and instead add a "-a" to show all items. I, personally, would be using "-F" almost always because I'm not interested in items that are fine. And the more nodes you're checking in one run, the more important "-F" gets. It's just too noisy to see each and every item.

(At work, I've been using `bw verify groupfoo | grep '✘'` *a lot*.)

**Comment by trehn** [comment]
Merged. I have created a new issue for switching to `-a` with 2.0.
