### ISSUE TITLE
retroactively add "introduced in version X.Y" markers to docs

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#184]

**Comment by vain** [comment]
Well, since this has been stale for almost 10 years now, it’s going to be a ton of work.

Honestly, not sure if it’s worth it. This information would be very helpful if you had one BundleWrap repo that you would pass around to lots of people, all of them potentially running different bw versions, so you want to know which bw features you can safely use.

I don’t think that people really do that, do they? 🤔 I’d suspect almost everybody uses the latest version anyway.

I’m going to close this for now.
