### ISSUE TITLE
support for augeas

### ISSUE THREAD

**Issue by bkendinibilir** [bundlewrap/bundlewrap#269]
It would be great to modify files on bw nodes with augeas syntax. The main advantage over templates is that you don't have to know and maintain the full content of the managed file.

**Comment by trehn** [comment]
* installing augeas on a node is a no-go, must be local optional dep
* Python bindings suck (unmaintained, still have to install lib manually), must shell out
* has to be integrated into file item
* remote file is downloaded to local tmpdir (which becomes AUGEAS_ROOT), `augtool -f` is used to feed commands, modified file is now "rendered"
* command file is taken from `source` file attribute like a regular template
* command file has to be templated itself, so augeas is probably not a template engine, but a special flag
* also must be able to select lens
* since only one file can be edited at a time, there's a lot of repeated, useless paths in the command file
* plenty of ways for users to violate idempotency

**Comment by trehn** [comment]
Started working on it, but it just doesn't feel right. Augeas works OK for structured data like XML or JSON and maybe INI, but so many things beyond that (like the simple "line in file" use case) are very hard (or even impossible) to implement in an idempotent fashion.
