### ISSUE TITLE
^D in Interactive Mode Ends Interactive Mode and Assumes "Yes" to All

### ISSUE THREAD

**Issue by j-frost** [bundlewrap/bundlewrap#391]
When sending a ^D to bundlewrap while in apply -i mode, bundlewrap stops interactive mode, and instead assumes "yes" to all further changes. 

I did not expect this. I assumed that EOF would mean that it's uncertain what the user would have answered to all further queries, so bundlewrap would stop applying changes in that instance.

**Comment by vain** [comment]
A "lazy fix" would be:

```diff
diff --git a/bundlewrap/utils/ui.py b/bundlewrap/utils/ui.py
index 6789204..d702076 100644
--- a/bundlewrap/utils/ui.py
+++ b/bundlewrap/utils/ui.py
@@ -156,7 +156,13 @@ class DrainableStdin(object):
             if QUIT_EVENT.is_set():
                 return None
             if select([sys.stdin], [], [], 0.1)[0]:
-                return sys.stdin.readline().strip()
+                answer = sys.stdin.readline()
+                # If we read an empty string, then the user pressed ^D
+                # at the prompt without typing anything else. We ignore
+                # that. A user must either enter some proper line or he
+                # must hit ^C to abort.
+                if answer != "":
+                    return answer.strip()
 
     def drain(self):
         if sys.stdin.isatty():
```

This makes bw ignore ^D if there is no other input.

If the user *did* enter something before hitting ^D, you get some garbled output from bw (the line saying "please answer with 'y(es)' or 'n(o)'" is missing a leading newline), but nothing bad happens. And you would have to hit ^D twice because `readline()` continues to read until it reaches end of line or "EOF" (i.e., `read()` returns 0). All that is a little awkward, but I highly doubt that people regularly enter stuff and then hit ^D -- I suspect that few people even know what ^D actually does.

The "proper fix" could probably be something like this (i.e., do the same thing that the `SIGINT` handler does):

```diff
diff --git a/bundlewrap/utils/ui.py b/bundlewrap/utils/ui.py
index 6789204..489ed9b 100644
--- a/bundlewrap/utils/ui.py
+++ b/bundlewrap/utils/ui.py
@@ -151,12 +151,19 @@ def write_to_stream(stream, msg):
 
 
 class DrainableStdin(object):
+    def __init__(self, shutdown_event_soft):
+        self.shutdown_event_soft = shutdown_event_soft
+
     def get_input(self):
         while True:
             if QUIT_EVENT.is_set():
                 return None
             if select([sys.stdin], [], [], 0.1)[0]:
-                return sys.stdin.readline().strip()
+                answer = sys.stdin.readline()
+                if answer != "":
+                    return answer.strip()
+                else:
+                    self.shutdown_event_soft.set()
 
     def drain(self):
         if sys.stdin.isatty():
@@ -207,7 +214,10 @@ class IOManager(object):
         if TTY:
             write_to_stream(STDOUT_WRITER, HIDE_CURSOR)
 
-    def ask(self, question, default, epilogue=None, input_handler=DrainableStdin()):
+    def ask(self, question, default, epilogue=None, input_handler=None):
+        if input_handler is None:
+            input_handler = DrainableStdin(SHUTDOWN_EVENT_SOFT)
+
         assert self._active
         answers = _("[Y/n]") if default else _("[y/N]")
         question = question + " " + answers + " "
```

… which begs the question whether we really want to *abandon mission* on ^D. I've played with this a little bit and it feels more natural to just do nothing on ^D. If I want to abort, I hit ^C. ^C means ABORT ABORT ABORT in all tools. ^D is not that "well defined". ^D actually means "flush" and it just happens to look like "EOF" to the process calling `read()` if there has been no input yet. It's usually used to signal the end of input and to mean, "okay, I'm done typing text, so please continue and process that text" (in my view of the world, at least). So, it's not really ABORT ABORT, is it?

Plus, if ^D just does nothing, I suspect that the user will automatically try ^C next.

**Comment by j-frost** [comment]
I agree insofar that ^D is not really an abort signal. That said, in my mind, even when interpreting ^D as "I'm done entering text, so please process what you have and leave me in peace", that really shouldn't cause behavior similar to `apt`'s `--yes`. 

Also, (and this is afaik, so reader beware) isn't ^D just 0x4? I believe most modern TTYs and subsequently terminal emulators interpret it to actually signify EoF for them. I mean I know there's some *really* funky setups out there, but is that really a use case we have to account for here? `-i` is, after all, an interactive mode. 

I'd prefer ^D to quit honestly, because that'd be consistent with most shells; but I'm fine with any change that prevents `-y`-like behavior.

**Comment by trehn** [comment]
Why is the current behavior so unexpected? While not deliberate, I find it useful and semantically sound. You're sending EOF, or more precisely: End of Input. You're telling an interactive program that you do not want to quit (that would've been ^C), but you don't want to make any further input either. I find it perfectly reasonable for the program to just assume the default answer (which is Yes) from then on.

**Comment by j-frost** [comment]
I guess it feels unfamiliar because f.i. `apt` behaves differently. From there, my brain just wanders and extrapolates to all the world. If this project consciously chooses to do things differently that's fine and well-reasoned. I guess maybe include it in the docs and be done with it. 

```shell
j-frost@mytesthost-1 ~ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  tzdata
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 264 kB of archives.
After this operation, 2,048 B of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
```
(when sending ^D to an `apt upgrade` without `-y`)
