### ISSUE TITLE
'groups' attribute for nodes

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#464]
To define group membership directly at the node itself.

**Comment by trehn** [comment]
This provides similar functionality as `template_node`: https://docs.bundlewrap.org/repo/nodes.py/#template_node

There are some problems with `template_node`: If the template node is a dummy, you have to explicitly un-dummy every node created from it. Also, there can be only one template node per node (while we could assign multiple groups).

Should we remove `template_node` in 4.0 in favor of this? The original idea behind `template_node` was to be able to duplicate nodes with minimum effort. However, I haven't seen it used in practice.

**Comment by vain** [comment]
Nuke `template_node`.

`template_node` may be useful in this scenario: You want to clone a system, quickly, temporarily, throw it away in a few minutes. So, you create a new node file and set `template_node`. But which metadata/attributes do you have to overwrite in order to not create conflicts with the real node? You don’t really know, so you scan through the original node and copy parts of it to your temporary node. This is a clunky workflow. You might just as well copy the whole original node file and then edit the new file.

I don’t think `template_node` should be used in any *permanent* setups. That’s what groups are for. The only advantage of `template_node` was that you could set it *at the node*, which this PR finally allows for proper groups.

So, nuke it.
