### ISSUE TITLE
the case against a default for Metastack.get()

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#482]
So the original intention of `Metastack.get()` was to force users to provide a default, so they would write their reactors in a way that makes moving any metadata from a static source to a reactor possible without having to touch other reactors working with that metadata.

One problem is that it will require people to duplicate defaults from `@metadata_defaults`.

Another problem is that with large, segmented datastructures (think `nginx/sites`), you quickly end up working with plain dicts again: 

```
domains = set()
for name, config in metadata.get('nginx/sites').items():
     domains.update(config['alias_domains'])  # look ma, no default!
```

**Comment by trehn** [comment]
Consider the case where you need some advanced logic to determine the `primary_network_interface` for a node. Instead of making up a quasi-nonsensical default of `eth0` everywhere, wouldn't it be better to `return EXPECT_RESULT` instead and just wait for the correct interface to appear?

Could we make this automatic? Say a reactor calls `metadata.get('primary_network_interface')`. Initially that raises a special kind of `KeyError` which is treated much like `EXPECT_RESULT`. If we neved get any other return value from that reactor, we can even alert the user it never found `primary_network_interface`.

**Comment by trehn** [comment]
Could we even be so bold to do that with plain `KeyError`s? Then it would work even for `config['alias_domains']` above.

**Comment by trehn** [comment]
When doing this, what are remaining legitimate use cases for `Metastack.has()`?

**Comment by vain** [comment]
> When doing this, what are remaining legitimate use cases for Metastack.has()?

I don’t see any, either – in the following scenario.

Suppose we ban all defaults to `@metadata_defaults`. In `metadata.get()`, you are no longer able to provide a default. (IIRC, defaults were just made *optional* in our last discussion.)

Yes, it’s a bit clunky for very simple metaprocs, but also much cleaner. Defaults are now documented automatically and consistently. Reactors just use `metadata['foo']` and get rescheduled if there’s a key error – and as you said, we automatically catch those “expected result” cases.

If we force users to always declare their defaults, we could even remove all the `.get()` stuff from items.py and templates.

I have a tendency to dislike too many options. :-) Always put defaults in `@metadata_defaults`, always access metadata as `foo['bar']`. Simple.

Of course, this breaks in your nginx example above (because users can then use `my_subdict.get('oink', 'boink')` again). We already freeze objects returned from Metastacks, so maybe never return plain dicts while we’re at it?

**Comment by trehn** [comment]
> I have a tendency to dislike too many options. :-) Always put defaults in `@metadata_defaults`, always access metadata as `foo['bar']`. Simple.

I don't think it's that simple:

>Of course, this breaks in your nginx example above (because users can then use my_subdict.get('oink', 'boink') again).

If we prevent that, where would 'boink' ever come from? We cannot put it in `@metadata_defaults` because of the nested nature of `nginx/sites`.

Unless we find a practical way to define some sort of template for `nginx/sites/example.com`, we're out of luck. People could do something like this:

```
SITE_TEMPLATE = {
    'tls': True,
}

@metadata_defaults
def defaults():
    return {'nginx': {'sites': {}}}

@metadata_reactor
def foo(metadata):
    for name, config in metadata.get('nginx/sites').items():
        config = SITE_TEMPLATE.copy().update(config)
        [...]
```

But I don't see us somehow providing this `SITE_TEMPLATE` as part of some mechanism with magic wildcard keys or something like that:

```
@metadata_defaults
def defaults():
    return {
        'nginx': {
            'sites': {
                '*': {
                   'tls': True,
                },
            },
        },
    }

@metadata_reactor
def foo(metadata):
    for name, config in metadata.get('nginx/sites').items():
        print(config['tls'])  # guaranteed to exist!
```

So we're stuck with `config.get('tls', True)`. Otherwise, we'd have to be very thorough and prevent any use of defaults in `items.py` or file templates as well. If we did that, every possible option would always have to be written to metadata, even if 90% of them would always be at their default value. Nice for being explicit, but bad for readability and quickly assessing what is special about a node.

**Comment by vain** [comment]
FTR: You are, of course, right and I am sad.
