### ISSUE TITLE
abort gracefully on CTRL+C

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#75]
CTRL+C again for hard abort

**Comment by vain** [comment]
I played with the idea we discussed today.

This prevents ssh from receiving `SIGINT` from the terminal and also catches it in our parent process:

```python
#!/usr/bin/env python

from os import setpgrp
from subprocess import PIPE, Popen
from signal import SIGINT, signal

def new_process_group():
    setpgrp()

def print_sigint(*args, **kwargs):
    print("SIGINT IN PYTHON")

signal(SIGINT, print_sigint)

p = Popen(
    ['ssh', 'my.node.com', 'sleep 10m'],
    preexec_fn=new_process_group,
    stdin=PIPE,
    stdout=PIPE,
    stderr=PIPE,
)
print(p.pid)
p.communicate()
print("Process finished")
```

Now, normally, our thread will block in `p.communicate()` and only return from that function if ssh exits. That's fine and that's what you'd expect from a "soft shutdown".

For a "hard shutdown", we'd have to manually send all of our ssh processes a signal. I simulated this by manually doing a `kill $sshpid` on the shell. Works fine, the code above returns from `p.communicate()` and the ssh process is gone. This means we'd have to collect all ssh PIDs in our main thread in order to send them a signal in case of a hard shutdown.

There's no easy way out here, like "kill all processes in our process group". That's exactly what `setpgrp()` prevents: It creates a new process group just for ssh, so it won't receive the `SIGINT` that's implicitly sent to the foreground process group. Also, there is no way to send a signal to all children.

Note that ignoring `SIGINT` in before `exec()`ing ssh is useless, too: ssh resets the signal handler. Instead, we must take care that it never receives the signal in the first place.

And, another idea: We could just kill all of bw's threads, wouldn't this kill ssh, too? No, it doesn't.

(Careful, that little snippet above can easily fool you. It's just that "ssh multiplexing master doesn't close stderr" thingy again. If your ssh appears to never return, that's why.)

**Comment by vain** [comment]
Aww, too bad, multiplexing breaks everything. Even when there's already a master running.

I'm ending up with an ssh zombie. Python doesn't care about the `SIGCHLD` it receives.

Will have to investigate ...
